### ISSUE TITLE
Using rice in the fun/bin/food script messes up terminal colors

### ISSUE THREAD

**Issue by vxid** [xero/dotfiles#10]
My guess is that some color code is not properly escaped.  Calling anything else with the same script fixes the problem.

![2017-08-03-200148_3840x1080_scrot](https://user-images.githubusercontent.com/16440823/28936021-a8aef624-7886-11e7-89f0-6e28736e4054.png)

**Comment by branderxero** [comment]
nice catch. i added `\e[0m` to the end of each. thanx

**Comment by xero** [comment]
nice catch. i added `\e[0m` to the end of each. thanx
