### ISSUE TITLE
Envy Code R license

### ISSUE THREAD

**Issue by needfulthing** [xero/dotfiles#12]
This font is not allowed to be redistributed either by other web sites or be included in a package, download, product or source repository. See https://damieng.com/blog/2008/05/26/envy-code-r-preview-7-coding-font-released and https://www.fontsquirrel.com/fonts/envy-code-r

**Comment by xero** [comment]
hello, you're correct. and keeping fonts in this repo makes no sense. i actually haven't used envy in a while anyhow.

i've added a note in the readme about my font setup to replace the files.
https://github.com/xero/dotfiles/commit/75d1533fed35a1e03e6058db590af683b6fe7de3
