### ISSUE TITLE
greybeard/neongold themes for vim?

### ISSUE THREAD

**Issue by bam80** [xero/dotfiles#13]
Thanks for accumulating all of this!
Don't you know if greybeard theme for vim exists? Didn't find it

**Comment by bam80** [comment]
Also, I would love this neongold.theme to be in Vim!
https://raw.githubusercontent.com/xero/dotfiles/master/previews/neongold.png

**Comment by xero** [comment]
so, greybeard was actually the precursor to [sourcerer](https://sourcerer.xero.nu). neongold is just an irssi theme that doesn't have it's own colors (it relies on your shell's). in [this shot](https://raw.githubusercontent.com/xero/dotfiles/master/previews/neongold.png) i'm actually also using [sourcerer](https://github.com/xero/dotfiles/blob/master/urxvt/sourcerer.Xcolors). here's the [vim package](https://github.com/xero/sourcerer.vim) ;D
