### ISSUE TITLE
understanding gnu stow

### ISSUE THREAD

**Issue by ElModdy** [xero/dotfiles#14]
Hi,
I'm new to Stow and I'm having difficulties understanding how to manage the dotfiles properly.
My quest is: If you have to add a file, do you create it in the repo and then relaunch stow every time?
I know my question is off topic and I will remove it if you don't want to answare me but I really appreciate any kind of help.

**Comment by xero** [comment]
hey, no worries.

stow is an on demand tool. when you run the command it looks in the specified directory for files then symlinks them into the target location. if you edit one of the source files already linked the changes are immediate. but if you create a new file the symlinks are not created yet until you run stow (again). 

hope that helps! i wrote [a blog post](https://blog.xero.nu/managing_dotfiles_with_gnu_stow) about my workflow that includes a number of stow examples.
