### ISSUE TITLE
Consider making an install script

### ISSUE THREAD

**Issue by serpro69** [xero/dotfiles#15]
Hi,

I like your setup and colors, especially nord colors :) Very nice job. 
I would like to use it but it still requires quite a bit of manual work to install all the packages, etc. Would you consider making a shell script to bootstrap everything? 
Thanks!

**Comment by xero** [comment]
hey, thanx for the suggestion.

[as detailed in the readme](https://github.com/xero/dotfiles/blob/master/README.md#installing), i use stow to symlink the files into place. each machine i bootstrap has a different use case, so i don't always need every tool or their configs on every box i clone them onto. the manual process is more aligned w/ my personal workflow.

as for installing required tools; sadly not all the distros i use are on the same page w/ package nomenclature. and i dont really want to maintain a bunch of dependency lists. i use so many tools as well, i'd have to filter our all the stuff that's not related to my dotfiles. sorry.
