### ISSUE TITLE
question - where did you get the unicode in the tmux and nvim

### ISSUE THREAD

**Issue by KeithETruesdell** [xero/dotfiles#23]
I love what you have here, and I have taken some things from it, thank you.  I have been looking for a good place to find some good unicode for a few things while customizing my own tmux and nvim.  Where did you get yours from?
Specifically, I am looking for angle brackets, half circles and such that are full line height.

**Comment by xero** [comment]
here, there, and everywhere! as a text artist i find inspo in a lot of places.

that being said my classic "dividers" are [unicode block shading characters](https://www.w3.org/TR/xml-entity-names/025.html) █ ▓ ▒ ░ 

i use a "[nerd font](https://github.com/ryanoasis/nerd-fonts)" version of the [hack typeface](https://github.com/source-foundry/Hack). empty unicode blocks in the font are replaced with cool icons. you can easily search for them using their [cheet sheet](http://nerdfonts.com/cheat-sheet).


hope that helps!
