### ISSUE TITLE
'Rusto' figlet font

### ISSUE THREAD

**Issue by ijks** [xero/dotfiles#4]
I noticed in xero_shell.gif and in [aliases.zsh](https://github.com/xero/dotfiles/blob/master/zsh/.zsh/aliases.zsh#l50) that you used a font called Rusto, but I can't find it anywhere, and it did not come installed with toilet on my system (Arch). Did you make it yourself? It's really pretty and I want it. :p

**Comment by xero** [comment]
@ijks yes, custom. i have a lot more in the works. here ya go: http://git.io/.figletfonts

i added rusto and rustofat (the bold version).

**Comment by xero** [comment]
```
┳━┓┏┓┓  ┳┏━┓┓ ┳┓
┣━ ┃┃┃┏ ┃┃ ┃┗┏┛┃
┻━┛┇┗┛┗━┇┛━┛ ┇ o
```

**Comment by ijks** [comment]
Awesome, thanks! :+1:
