### ISSUE TITLE
GNU Stow

### ISSUE THREAD

**Issue by dmarcoux** [xero/dotfiles#6]
Hello,

I have one question about GNU Stow. I learned, thanks to you, how to use GNU Stow with the -t option like this `stow -t / my_folder`. I am wondering how can I unstow it? I tried `stow -D my_folder` and `stow -D / my_folder`, but it doesn't work. Do you have any idea how to do this?

Thanks!

**Comment by xero** [comment]
hey,
all you need to do is combine the arguments.

say you have this setup:
```
[/tmp/stowtest]── - tree ../
../
└── stowtest/
    └── bin/
        └── file

2 directories, 1 file
```
if you stow the bin folder:
```
[/tmp/stowtest]── - stow bin
[/tmp/stowtest]── - tree ../
../
├── stowtest/
│   └── bin/
│       └── file
└── file -> stowtest/bin/file

2 directories, 2 files
```
to remove use the `D` flag:
```
[/tmp/stowtest]── - stow -D bin
[/tmp/stowtest]── - tree ../
../
└── stowtest/
    └── bin/
        └── file

2 directories, 1 file
```
to stow to another location use the `t` flag with a target location:
```
[/tmp/stowtest]── - mkdir somewhere
[/tmp/stowtest]── - stow bin -t ./somewhere
[/tmp/stowtest]── - tree ../
../
└── stowtest/
    ├── bin/
    │   └── file
    └── somewhere/
        └── file -> ../bin/file

3 directories, 2 files
```
you can remove it by using both the `D` and `t` flags:
```
[/tmp/stowtest]── - stow -D bin -t ./somewhere
[/tmp/stowtest]── - tree ../
../
└── stowtest/
    ├── bin/
    │   └── file
    └── somewhere/

3 directories, 1 file
[/tmp/stowtest]── -
```

hope that helps

**Comment by dmarcoux** [comment]
It works well, thank you! Have a great day.
