### ISSUE TITLE
Looking for the Super Mario wallpaper

### ISSUE THREAD

**Issue by qzchenwl** [xero/dotfiles#7]
Hello xero,

I like this wallpaper a lot!
![](https://raw.githubusercontent.com/xero/dotfiles/master/previews/blizzard-orb.png)

But I cannot find it in `wallpaper/`. Could you please share that?

Thanks! :)

**Comment by xero** [comment]
[here](https://github.com/xero/dotfiles/commit/4b006067021f6e6cc947920661b8dba724fb28f1) ya go! [normal](https://raw.githubusercontent.com/xero/dotfiles/4b006067021f6e6cc947920661b8dba724fb28f1/wallpaper/classic.png) and [double](https://raw.githubusercontent.com/xero/dotfiles/4b006067021f6e6cc947920661b8dba724fb28f1/wallpaper/classic-double.png) sized
